import "./globals.css"
import { Montserrat } from "@next/font/google"
import { Oswald } from "@next/font/google"
import Navbar from "./components/Navbar"

const montserrat = Montserrat({
  weights: [400, 700],
  subsets: ["latin"],
  variable: "--font-montserrat",
})

const oswald = Oswald({
  weights: [400, 700],
  subsets: ["latin"],
  variable: "--font-oswald",
})

export const metadata = {
  title: "Next 13 Experiment",
  description: "Generated by Erik Robles",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-montserrat `}>
        <Navbar />
        <main className="mx-32 my-12 mt-[90px]">{children}</main>
      </body>
    </html>
  )
}
